### PR TITLE
Update ccmod.json

### PR DESCRIPTION
**Pull request by krypciak**
A new `ccmod.json` standard now requires these fields I added.
Please create a new release or update the release `.ccmod` after merging.

### CODE REVIEW

**Review by Inevitabilis — CHANGES_REQUESTED** [review]
damn, didn't think anyone will remember of it
 may i ask you to add dmitmel as an author as well? they did all the code side

**Comment by krypciak** [comment]
There you go

**Review by Inevitabilis — APPROVED** [review]

**Comment by Inevitabilis** [comment]
thank you!

**Comment by krypciak** [comment]
Remember to make a new release

**Pull request merged**
